-- MySQL Script generated by MySQL Workbench
-- Thu Dec  5 12:47:19 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jvln
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `jvln` ;

-- -----------------------------------------------------
-- Schema jvln
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jvln` DEFAULT CHARACTER SET utf8 ;
USE `jvln` ;

-- -----------------------------------------------------
-- Table `jvln`.`credentials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jvln`.`credentials` ;

CREATE TABLE IF NOT EXISTS `jvln`.`credentials` (
  `pk` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(255) NULL,
  `password_hashed` VARCHAR(255) NULL,
  PRIMARY KEY (`pk`),
  UNIQUE INDEX `pk_UNIQUE` (`pk` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jvln`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jvln`.`users` ;

CREATE TABLE IF NOT EXISTS `jvln`.`users` (
  `pk` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cred_pk` INT UNSIGNED NOT NULL,
  `name_last` VARCHAR(255) NULL,
  `name_first` VARCHAR(255) NULL,
  PRIMARY KEY (`pk`),
  UNIQUE INDEX `pk_UNIQUE` (`pk` ASC),
  UNIQUE INDEX `cred_pk_UNIQUE` (`cred_pk` ASC),
  CONSTRAINT `users_cred_pk_fk`
    FOREIGN KEY (`cred_pk`)
    REFERENCES `jvln`.`credentials` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jvln`.`files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jvln`.`files` ;

CREATE TABLE IF NOT EXISTS `jvln`.`files` (
  `pk` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `file_name` VARCHAR(255) NOT NULL,
  `file_id` VARCHAR(45) NULL,
  `path` VARCHAR(255) NULL,
  `scans_n` INT NULL,
  PRIMARY KEY (`pk`),
  UNIQUE INDEX `pk_UNIQUE` (`pk` ASC),
  INDEX `file_index` (`file_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jvln`.`methods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jvln`.`methods` ;

CREATE TABLE IF NOT EXISTS `jvln`.`methods` (
  `pk` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `parameters` LONGBLOB NOT NULL,
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`pk`),
  UNIQUE INDEX `pk_UNIQUE` (`pk` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jvln`.`scans`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jvln`.`scans` ;

CREATE TABLE IF NOT EXISTS `jvln`.`scans` (
  `pk` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `file_pk` INT UNSIGNED NOT NULL,
  `method_pk` INT UNSIGNED NOT NULL,
  `scan_id` INT UNSIGNED NOT NULL,
  `title` VARCHAR(255) NULL,
  `rt_sec` FLOAT NULL,
  `pre_mz` FLOAT NULL,
  `pre_z` INT NULL,
  `pre_int` FLOAT NULL,
  `ms_it_sec` FLOAT NULL,
  `ms_ct` VARCHAR(16) NULL,
  `ms_ce` FLOAT NULL,
  `peaks` LONGBLOB NULL,
  `spectrum` LONGBLOB NULL,
  `int_rsd` FLOAT NULL,
  `int_rad` FLOAT NULL,
  `int_iqr` FLOAT NULL,
  `int_ntp` FLOAT NULL,
  `int_prd` FLOAT NULL,
  `t_peaks` INT NULL,
  `n_peaks` INT NULL,
  `spec_fcorr` FLOAT NULL,
  `spec_prob` FLOAT NULL,
  PRIMARY KEY (`pk`),
  UNIQUE INDEX `pk_UNIQUE` (`pk` ASC),
  INDEX `precursor_index` (`rt_sec` ASC, `pre_mz` ASC, `pre_z` ASC),
  INDEX `quality_index` (`spec_fcorr` ASC, `spec_prob` ASC, `n_peaks` ASC, `t_peaks` ASC),
  INDEX `files_pk_fk_idx` (`file_pk` ASC),
  INDEX `methods_pk_fk_idx` (`method_pk` ASC),
  CONSTRAINT `files_pk_fk`
    FOREIGN KEY (`file_pk`)
    REFERENCES `jvln`.`files` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `scan_methods_pk_fk`
    FOREIGN KEY (`method_pk`)
    REFERENCES `jvln`.`methods` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jvln`.`psms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jvln`.`psms` ;

CREATE TABLE IF NOT EXISTS `jvln`.`psms` (
  `pk` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `scan_pk` INT UNSIGNED NOT NULL DEFAULT 0,
  `method_pk` INT UNSIGNED NOT NULL DEFAULT 0,
  `peptide` VARCHAR(255) NOT NULL DEFAULT 'na',
  `pre_mma` FLOAT NOT NULL DEFAULT 0,
  `psm_mma` FLOAT NOT NULL DEFAULT 0,
  `psm_z` FLOAT UNSIGNED NULL DEFAULT 0,
  `psm_i` INT UNSIGNED NULL DEFAULT 0,
  `psm_o` INT UNSIGNED NULL DEFAULT 0,
  `psm_score` FLOAT UNSIGNED NOT NULL DEFAULT 0,
  `psm_fcorr` FLOAT UNSIGNED NOT NULL DEFAULT 0,
  `psm_prob` FLOAT UNSIGNED NOT NULL DEFAULT 0,
  `hit_prob` FLOAT UNSIGNED NOT NULL DEFAULT 0,
  `rank_prob` FLOAT UNSIGNED NOT NULL DEFAULT 0,
  `hit_rank` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`pk`),
  UNIQUE INDEX `pk_UNIQUE` (`pk` ASC),
  INDEX `peptide_index` (`peptide` ASC),
  INDEX `psm_score_index` (`psm_prob` ASC, `pre_mma` ASC, `hit_rank` ASC),
  CONSTRAINT `scan_pk_fk`
    FOREIGN KEY (`scan_pk`)
    REFERENCES `jvln`.`scans` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `psms_methods_pk_fk`
    FOREIGN KEY (`method_pk`)
    REFERENCES `jvln`.`methods` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jvln`.`validations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jvln`.`validations` ;

CREATE TABLE IF NOT EXISTS `jvln`.`validations` (
  `pk` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `psm_pk` INT UNSIGNED NOT NULL,
  `fdr_metric` VARCHAR(45) NOT NULL,
  `method_pk` INT UNSIGNED NOT NULL,
  `fdr_eprob` FLOAT UNSIGNED NOT NULL,
  `fdr_prob` FLOAT UNSIGNED NULL,
  `fdr_qvalue` FLOAT UNSIGNED NULL,
  PRIMARY KEY (`pk`),
  UNIQUE INDEX `pk_UNIQUE` (`pk` ASC),
  INDEX `perf_index` (`fdr_eprob` ASC, `fdr_prob` ASC, `fdr_qvalue` ASC),
  INDEX `psms_pk_fk_idx` (`psm_pk` ASC),
  INDEX `methods_pk_fk_idx` (`method_pk` ASC),
  CONSTRAINT `psms_pk_fk`
    FOREIGN KEY (`psm_pk`)
    REFERENCES `jvln`.`psms` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pref_methods_pk_fk`
    FOREIGN KEY (`method_pk`)
    REFERENCES `jvln`.`methods` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jvln`.`accesses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jvln`.`accesses` ;

CREATE TABLE IF NOT EXISTS `jvln`.`accesses` (
  `pk` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_pk` INT UNSIGNED NOT NULL,
  `file_pk` INT UNSIGNED NOT NULL,
  `owner` TINYINT NOT NULL DEFAULT 0,
  `read` TINYINT NOT NULL DEFAULT 0,
  `write` TINYINT NOT NULL DEFAULT 0,
  `delete` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`pk`),
  UNIQUE INDEX `pk_UNIQUE` (`pk` ASC),
  INDEX `accesses_users_fk_idx` (`user_pk` ASC),
  INDEX `accesses_files_fk_idx` (`file_pk` ASC),
  CONSTRAINT `accesses_users_fk`
    FOREIGN KEY (`user_pk`)
    REFERENCES `jvln`.`users` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `accesses_files_fk`
    FOREIGN KEY (`file_pk`)
    REFERENCES `jvln`.`files` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jvln`.`metrics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jvln`.`metrics` ;

CREATE TABLE IF NOT EXISTS `jvln`.`metrics` (
  `pk` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `file_pk` INT UNSIGNED NOT NULL,
  `metric` VARCHAR(45) NOT NULL,
  `n` INT NULL,
  `max` FLOAT NULL,
  `median` FLOAT NULL,
  `mean` FLOAT NULL,
  `min` FLOAT NULL,
  `q25` FLOAT NULL,
  `q75` FLOAT NULL,
  `q005` FLOAT NULL,
  `q995` FLOAT NULL,
  PRIMARY KEY (`pk`),
  INDEX `file_pk` (`file_pk` ASC),
  INDEX `metric` (`metric` ASC),
  CONSTRAINT `file_pk_fk`
    FOREIGN KEY (`file_pk`)
    REFERENCES `jvln`.`files` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jvln`.`psm_alts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jvln`.`psm_alts` ;

CREATE TABLE IF NOT EXISTS `jvln`.`psm_alts` (
  `pk` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `scan_pk` INT UNSIGNED NOT NULL DEFAULT 0,
  `peptide` VARCHAR(255) NOT NULL DEFAULT 'na',
  `pre_mma` FLOAT NOT NULL DEFAULT 0,
  `psm_mma` FLOAT NOT NULL DEFAULT 0,
  `psm_z` FLOAT UNSIGNED NULL DEFAULT 0,
  `psm_i` INT UNSIGNED NULL DEFAULT 0,
  `psm_o` INT UNSIGNED NULL DEFAULT 0,
  `psm_score` FLOAT UNSIGNED NOT NULL DEFAULT 0,
  `psm_fcorr` FLOAT UNSIGNED NOT NULL DEFAULT 0,
  `psm_prob` FLOAT UNSIGNED NOT NULL DEFAULT 0,
  `hit_prob` FLOAT UNSIGNED NOT NULL DEFAULT 0,
  `alt_prob` FLOAT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`pk`),
  UNIQUE INDEX `pk_UNIQUE` (`pk` ASC),
  INDEX `peptide_index` (`peptide` ASC),
  INDEX `psm_score_index` (`psm_prob` ASC, `pre_mma` ASC),
  CONSTRAINT `scan_pk_fk0`
    FOREIGN KEY (`scan_pk`)
    REFERENCES `jvln`.`scans` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jvln`.`experiments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jvln`.`experiments` ;

CREATE TABLE IF NOT EXISTS `jvln`.`experiments` (
  `pk` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `file_pk` INT UNSIGNED NOT NULL,
  `experiment_name` VARCHAR(255) NULL,
  PRIMARY KEY (`pk`),
  INDEX `file_pk` (`file_pk` ASC, `experiment_name` ASC),
  CONSTRAINT `exp_file_pk_fk`
    FOREIGN KEY (`file_pk`)
    REFERENCES `jvln`.`files` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
