-- MySQL Script generated by MySQL Workbench
-- Fri Dec 13 11:41:46 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema jvln
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jvln
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jvln` DEFAULT CHARACTER SET utf8 ;
USE `jvln` ;

-- -----------------------------------------------------
-- Table `jvln`.`files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jvln`.`files` (
  `pk` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `file_name` VARCHAR(255) NOT NULL,
  `file_id` VARCHAR(45) NULL DEFAULT NULL,
  `path` VARCHAR(255) NULL DEFAULT NULL,
  `scans_n` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`pk`),
  UNIQUE INDEX `pk_UNIQUE` (`pk` ASC),
  INDEX `file_index` (`file_name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 81
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jvln`.`credentials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jvln`.`credentials` (
  `pk` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(255) NULL DEFAULT NULL,
  `password_hashed` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`pk`),
  UNIQUE INDEX `pk_UNIQUE` (`pk` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jvln`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jvln`.`users` (
  `pk` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `cred_pk` INT(10) UNSIGNED NOT NULL,
  `name_last` VARCHAR(255) NULL DEFAULT NULL,
  `name_first` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`pk`),
  UNIQUE INDEX `pk_UNIQUE` (`pk` ASC),
  UNIQUE INDEX `cred_pk_UNIQUE` (`cred_pk` ASC),
  CONSTRAINT `users_cred_pk_fk`
    FOREIGN KEY (`cred_pk`)
    REFERENCES `jvln`.`credentials` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jvln`.`accesses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jvln`.`accesses` (
  `pk` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_pk` INT(10) UNSIGNED NOT NULL,
  `file_pk` INT(10) UNSIGNED NOT NULL,
  `owner` TINYINT(4) NOT NULL DEFAULT '0',
  `read` TINYINT(4) NOT NULL DEFAULT '0',
  `write` TINYINT(4) NOT NULL DEFAULT '0',
  `delete` TINYINT(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`pk`),
  UNIQUE INDEX `pk_UNIQUE` (`pk` ASC),
  INDEX `accesses_users_fk_idx` (`user_pk` ASC),
  INDEX `accesses_files_fk_idx` (`file_pk` ASC),
  CONSTRAINT `accesses_files_fk`
    FOREIGN KEY (`file_pk`)
    REFERENCES `jvln`.`files` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `accesses_users_fk`
    FOREIGN KEY (`user_pk`)
    REFERENCES `jvln`.`users` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jvln`.`experiments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jvln`.`experiments` (
  `pk` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `file_pk` INT(10) UNSIGNED NOT NULL,
  `experiment_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`pk`),
  INDEX `file_pk` (`file_pk` ASC, `experiment_name` ASC),
  CONSTRAINT `exp_file_pk_fk`
    FOREIGN KEY (`file_pk`)
    REFERENCES `jvln`.`files` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 81
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jvln`.`methods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jvln`.`methods` (
  `pk` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `parameters` LONGBLOB NOT NULL,
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`pk`),
  UNIQUE INDEX `pk_UNIQUE` (`pk` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 279
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jvln`.`metrics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jvln`.`metrics` (
  `pk` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `file_pk` INT(10) UNSIGNED NOT NULL,
  `metric` VARCHAR(45) NOT NULL,
  `n` INT(11) NULL DEFAULT NULL,
  `max` FLOAT NULL DEFAULT NULL,
  `median` FLOAT NULL DEFAULT NULL,
  `mean` FLOAT NULL DEFAULT NULL,
  `min` FLOAT NULL DEFAULT NULL,
  `q25` FLOAT NULL DEFAULT NULL,
  `q75` FLOAT NULL DEFAULT NULL,
  `q005` FLOAT NULL DEFAULT NULL,
  `q995` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`pk`),
  INDEX `file_pk` (`file_pk` ASC),
  INDEX `metric` (`metric` ASC),
  CONSTRAINT `file_pk_fk`
    FOREIGN KEY (`file_pk`)
    REFERENCES `jvln`.`files` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1905
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jvln`.`scans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jvln`.`scans` (
  `pk` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `file_pk` INT(10) UNSIGNED NOT NULL,
  `method_pk` INT(10) UNSIGNED NOT NULL,
  `scan_id` INT(10) UNSIGNED NOT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `rt_sec` FLOAT NULL DEFAULT NULL,
  `pre_mz` FLOAT NULL DEFAULT NULL,
  `pre_z` INT(11) NULL DEFAULT NULL,
  `pre_int` FLOAT NULL DEFAULT NULL,
  `ms_it_sec` FLOAT NULL DEFAULT NULL,
  `ms_ct` VARCHAR(16) NULL DEFAULT NULL,
  `ms_ce` FLOAT NULL DEFAULT NULL,
  `peaks` LONGBLOB NULL DEFAULT NULL,
  `spectrum` LONGBLOB NULL DEFAULT NULL,
  `int_rsd` FLOAT NULL DEFAULT NULL,
  `int_rad` FLOAT NULL DEFAULT NULL,
  `int_iqr` FLOAT NULL DEFAULT NULL,
  `int_ntp` FLOAT NULL DEFAULT NULL,
  `int_prd` FLOAT NULL DEFAULT NULL,
  `t_peaks` INT(11) NULL DEFAULT NULL,
  `n_peaks` INT(11) NULL DEFAULT NULL,
  `spec_fcorr` FLOAT NULL DEFAULT NULL,
  `spec_prob` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`pk`),
  UNIQUE INDEX `pk_UNIQUE` (`pk` ASC),
  INDEX `precursor_index` (`rt_sec` ASC, `pre_mz` ASC, `pre_z` ASC),
  INDEX `quality_index` (`spec_fcorr` ASC, `spec_prob` ASC, `n_peaks` ASC, `t_peaks` ASC),
  INDEX `files_pk_fk_idx` (`file_pk` ASC),
  INDEX `methods_pk_fk_idx` (`method_pk` ASC),
  CONSTRAINT `files_pk_fk`
    FOREIGN KEY (`file_pk`)
    REFERENCES `jvln`.`files` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `scan_methods_pk_fk`
    FOREIGN KEY (`method_pk`)
    REFERENCES `jvln`.`methods` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 600969
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jvln`.`psm_alts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jvln`.`psm_alts` (
  `pk` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `scan_pk` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `peptide` VARCHAR(255) NOT NULL DEFAULT 'na',
  `pre_mma` FLOAT NOT NULL DEFAULT '0',
  `psm_mma` FLOAT NOT NULL DEFAULT '0',
  `psm_z` FLOAT UNSIGNED NULL DEFAULT '0',
  `psm_i` INT(10) UNSIGNED NULL DEFAULT '0',
  `psm_o` INT(10) UNSIGNED NULL DEFAULT '0',
  `psm_score` FLOAT UNSIGNED NOT NULL DEFAULT '0',
  `psm_fcorr` FLOAT UNSIGNED NOT NULL DEFAULT '0',
  `psm_prob` FLOAT UNSIGNED NOT NULL DEFAULT '0',
  `hit_prob` FLOAT UNSIGNED NOT NULL DEFAULT '0',
  `alt_prob` FLOAT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`pk`),
  UNIQUE INDEX `pk_UNIQUE` (`pk` ASC),
  INDEX `peptide_index` (`peptide` ASC),
  INDEX `psm_score_index` (`psm_prob` ASC, `pre_mma` ASC),
  INDEX `scan_pk_fk0` (`scan_pk` ASC),
  CONSTRAINT `scan_pk_fk0`
    FOREIGN KEY (`scan_pk`)
    REFERENCES `jvln`.`scans` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 212853
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jvln`.`psms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jvln`.`psms` (
  `pk` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `scan_pk` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `method_pk` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `peptide` VARCHAR(255) NOT NULL DEFAULT 'na',
  `pre_mma` FLOAT NOT NULL DEFAULT '0',
  `psm_mma` FLOAT NOT NULL DEFAULT '0',
  `psm_z` FLOAT UNSIGNED NULL DEFAULT '0',
  `psm_i` INT(10) UNSIGNED NULL DEFAULT '0',
  `psm_o` INT(10) UNSIGNED NULL DEFAULT '0',
  `psm_score` FLOAT UNSIGNED NOT NULL DEFAULT '0',
  `psm_fcorr` FLOAT UNSIGNED NOT NULL DEFAULT '0',
  `psm_prob` FLOAT UNSIGNED NOT NULL DEFAULT '0',
  `hit_prob` FLOAT UNSIGNED NOT NULL DEFAULT '0',
  `rank_prob` FLOAT UNSIGNED NOT NULL DEFAULT '0',
  `hit_rank` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`pk`),
  UNIQUE INDEX `pk_UNIQUE` (`pk` ASC),
  INDEX `peptide_index` (`peptide` ASC),
  INDEX `psm_score_index` (`psm_prob` ASC, `pre_mma` ASC, `hit_rank` ASC),
  INDEX `scan_pk_fk` (`scan_pk` ASC),
  INDEX `psms_methods_pk_fk` (`method_pk` ASC),
  CONSTRAINT `psms_methods_pk_fk`
    FOREIGN KEY (`method_pk`)
    REFERENCES `jvln`.`methods` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `scan_pk_fk`
    FOREIGN KEY (`scan_pk`)
    REFERENCES `jvln`.`scans` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1493456
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jvln`.`validations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jvln`.`validations` (
  `pk` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `psm_pk` INT(10) UNSIGNED NOT NULL,
  `fdr_metric` VARCHAR(45) NOT NULL,
  `method_pk` INT(10) UNSIGNED NOT NULL,
  `fdr_eprob` FLOAT UNSIGNED NOT NULL,
  `fdr_prob` FLOAT UNSIGNED NULL DEFAULT NULL,
  `fdr_qvalue` FLOAT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`pk`),
  UNIQUE INDEX `pk_UNIQUE` (`pk` ASC),
  INDEX `perf_index` (`fdr_eprob` ASC, `fdr_prob` ASC, `fdr_qvalue` ASC),
  INDEX `psms_pk_fk_idx` (`psm_pk` ASC),
  INDEX `methods_pk_fk_idx` (`method_pk` ASC),
  CONSTRAINT `pref_methods_pk_fk`
    FOREIGN KEY (`method_pk`)
    REFERENCES `jvln`.`methods` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `psms_pk_fk`
    FOREIGN KEY (`psm_pk`)
    REFERENCES `jvln`.`psms` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1011913
DEFAULT CHARACTER SET = utf8;

USE `jvln` ;

-- -----------------------------------------------------
-- Placeholder table for view `jvln`.`summary_experiments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jvln`.`summary_experiments` (`experiment_name` INT, `n_files` INT, `n_scans` INT);

-- -----------------------------------------------------
-- procedure psms_by_fileid
-- -----------------------------------------------------

DELIMITER $$
USE `jvln`$$
CREATE DEFINER=`scbi`@`localhost` PROCEDURE `psms_by_fileid`(OUT param_01 char(32))
BEGIN
SELECT psms.pk pk, 
	  scan_id, rt_sec, pre_mz, pre_z, 
	  int_rsd, int_rad, int_iqr, int_ntp, 
	  spec_fcorr, spec_prob, 
	  pre_mma, psm_z, psm_i, psm_o, psm_mma, 
	  psm_score, psm_fcorr, 
	  psm_prob, hit_prob, rank_prob, hit_rank
	  FROM jvln.psms, jvln.scans, jvln.files
	  WHERE jvln.scans.file_pk = jvln.files.pk 
	  AND jvln.psms.scan_pk = jvln.scans.pk 
	  AND file_id = param_01;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `jvln`.`summary_experiments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jvln`.`summary_experiments`;
USE `jvln`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`scbi`@`localhost` SQL SECURITY DEFINER VIEW `jvln`.`summary_experiments` AS select `jvln`.`experiments`.`experiment_name` AS `experiment_name`,count(0) AS `n_files`,sum(`jvln`.`files`.`scans_n`) AS `n_scans` from (`jvln`.`experiments` join `jvln`.`files`) where (`jvln`.`experiments`.`file_pk` = `jvln`.`files`.`pk`) group by `jvln`.`experiments`.`experiment_name`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
